# Generated by Django 2.2.6 on 2019-10-26 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='Users name', max_length=150),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='no_pic.png', upload_to='prof_pic'),
        ),
    ]
