# Generated by Django 2.2.6 on 2019-10-28 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20191028_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='post.Post'),
        ),
    ]
